# .pre-commit-config.yaml
# Enforces consistent formatting, linting, typing. Mirrors CI.

minimum_pre_commit_version: "3.6.0"
default_stages: [pre-commit]
default_language_version:
  python: python3.11 # pre-commit hook envs use this interpreter

repos:
  # --- Python formatting & linting -----------------------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9 # keep in sync with pyproject
    hooks:
      - id: ruff-format
        name: ruff format
      - id: ruff
        name: ruff check
        args: [--fix]
        # Pin interpreter to avoid 3.14 stub/tooling drift
        language_version: python3.11

  # --- Type checking -------------------------------------------------------
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.1
    hooks:
      - id: mypy
        language_version: python3.11
        additional_dependencies:
          - types-requests
          - types-PyYAML
        args:
          - --ignore-missing-imports
          - --pretty
          - --show-error-codes
          - --cache-dir=.mypy_cache

  # --- General hygiene -----------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: detect-private-key
      - id: no-commit-to-branch
        args: [--branch, main]

  # --- Poetry lock consistency --------------------------------------------
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.3
    hooks:
      - id: poetry-check
      - id: poetry-lock
        stages: [manual] # run explicitly when you intend to update lock

  # --- Optional security / static analysis --------------------------------
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: [--quiet, --severity-level, medium]

  # --- Local hooks ---------------------------------------------------------
  - repo: local
    hooks:
      - id: pytest
        name: pytest (quick)
        entry: pytest -q
        language: system
        pass_filenames: false
        stages: [pre-push]
