# .pre-commit-config.yaml
# Enforces consistent formatting, linting, and typing before commit or push.
# Mirrors the CI pipeline to catch issues early.

repos:
  # --- Python formatting & linting -----------------------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9 # keep in sync with your pyproject.toml version
    hooks:
      - id: ruff
        name: ruff check
        args: [--fix] # auto-fix simple issues
      - id: ruff-format
        name: ruff format # code formatting (PEP8/Black-compatible)

  # --- Type checking -------------------------------------------------------
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-PyYAML
        args:
          - --ignore-missing-imports
          - --pretty
          - --show-error-codes

  # --- General hygiene -----------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]

  # --- Poetry lock consistency ---------------------------------------------
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.3
    hooks:
      - id: poetry-check
      - id: poetry-lock
        stages: [manual] # only run manually via `pre-commit run poetry-lock`

  # --- Optional security / static analysis ---------------------------------
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: [--quiet, --severity-level, medium]
